authors:

  halynagalanzina:
    name: Halyna Galanzina
    description: AI Solutions Architect & Founder of LITAI LLC
    avatar: https://avatars.githubusercontent.com/u/34709402?v=4
    url: https://www.linkedin.com/in/halyna-galanzina/