authors:

  halynagalanzina:
    name: Halyna Galanzina
    description: AI Solutions Architect & Founder of LITAI LLC
    avatar: https://github.com/identicons/halynagalanzina.png
    url: https://www.linkedin.com/in/halyna-galanzina/